#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II V
bspc monitor DP-0 III IV VI

bspc config border_width         0
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
xrandr --output HDMI-0 --primary && xrandr --output DP-0 --left-of HDMI-0
picom &
nitrogen --restore
xfce4-panel &
blueman-applet &
nm-applet &
